import type { Entrepreneur, FundingRound } from '@/types';

/**
 * Seed entrepreneurs.
 *
 * Mirrors the rows surfaced in the admin "Entrepreneurs" table and the
 * "Recently joined" dashboard card. The shape is deliberately close to a
 * DB row — `contentItemIds`, `programmeIds`, `sector` / `stage` are ids that
 * resolve against lookup tables. `trainerId` is legacy only; trainer scope is
 * inferred from content item ownership.
 */

const funding: Record<string, FundingRound[]> = {
  'e-paybridge': [
    { id: 'f-pb-1', name: 'Pre-seed (pre-BID)', amountUsd: 30000, date: '2023-01-15', source: 'Angel investor' },
    { id: 'f-pb-2', name: 'Grant – BID', amountUsd: 50000, date: '2023-06-10', source: 'BID grant', programmeId: 'p-accelerator-c6' },
    { id: 'f-pb-3', name: 'Seed', amountUsd: 40000, date: '2024-10-02', source: 'Angel investor', programmeId: 'p-readiness-fintech', goalId: 'goal-fundraising-series-a' },
  ],
  'e-healthfirst': [
    { id: 'f-hf-1', name: 'Series A', amountUsd: 300000, date: '2024-11-15', source: 'Institutional investor', programmeId: 'p-readiness-fintech' },
  ],
};

export const entrepreneurs: Entrepreneur[] = [
  {
    id: 'e-paybridge',
    businessName: 'PayBridge Africa Ltd',
    representative: 'Amara Osei',
    initials: 'PB',
    email: 'amara@paybridge.africa',
    phone: '+233 24 555 0172',
    country: 'Ghana',
    sector: 'fintech',
    stage: 'growth',
    cohort: 'Cohort 6',
    contentItemIds: ['c-intro-vid', 'c-intro-pdf', 'c-bmc-why', 'c-bmc-sheet', 'c-bmc-valueprop', 'c-bmc-tool', 'c-pitch-structure', 'c-pitch-qa', 'c-pitch-checklist', 'c-finmodel-basics', 'c-growth-ops-cadence', 'c-market-expansion-map', 'c-leadership-routines', 'c-export-checklist'],
    programmeIds: ['p-accelerator-c6', 'p-readiness-fintech', 'p-growth-ops', 'p-market-expansion', 'p-leadership-lab', 'p-export-readiness'],
    programmeId: 'p-accelerator-c6',
    source: 'invited',
    goal: {
      type: 'fundraising',
      amountUsd: 500000,
      description:
        'Raise Series A to expand into 2 new markets by Q4 2025.',
    },
    status: 'active',
    metrics: {
      trainingProgress: 68,
      deliverablesDone: 4,
      deliverablesTotal: 7,
      jobsCreated: 3,
      jobsWomen: 2,
      jobsMen: 1,
      fundsMobilisedUsd: 120000,
    },
    fundingRounds: funding['e-paybridge'],
    periodicUpdates: [
      {
        id: 'pu-pb-q4-2024',
        period: 'Q4 2024',
        periodStart: '2024-10-01',
        periodEnd: '2024-12-31',
        submittedAt: '2024-12-31',
        programmeId: 'p-accelerator-c6',
        jobsWomen: 2,
        jobsMen: 1,
        jobsCreated: 3,
        fundsMobilisedUsd: 0,
        notes: 'Maintained operations while preparing for investor outreach.',
      },
      {
        id: 'pu-pb-q3-2024',
        period: 'Q3 2024',
        periodStart: '2024-07-01',
        periodEnd: '2024-09-30',
        submittedAt: '2024-09-30',
        programmeId: 'p-readiness-fintech',
        jobsWomen: 0,
        jobsMen: 0,
        jobsCreated: 0,
        fundsMobilisedUsd: 0,
        notes: 'BID grant recorded in fundraising history and allocated to product development.',
      },
    ],
    lastUpdateAt: '2024-12-31',
    trainerId: 't-kofi',
    joinedAt: '2024-09-01',
  },
  {
    id: 'e-farmlink',
    businessName: 'FarmLink GH',
    representative: 'Kwame Mensah',
    initials: 'FL',
    email: 'kwame@farmlink.gh',
    phone: '+233 27 333 0190',
    country: 'Ghana',
    sector: 'agritech',
    stage: 'idea',
    cohort: 'Cohort 6',
    contentItemIds: ['c-intro-vid', 'c-intro-pdf', 'c-bmc-why', 'c-bmc-sheet', 'c-bmc-valueprop', 'c-growth-ops-cadence', 'c-market-expansion-map'],
    programmeIds: ['p-accelerator-c6', 'p-growth-ops', 'p-market-expansion'],
    programmeId: 'p-accelerator-c6',
    source: 'invited',
    goal: { type: 'milestone', description: 'Complete first pilot season' },
    status: 'active',
    metrics: {
      trainingProgress: 32,
      deliverablesDone: 1,
      deliverablesTotal: 7,
      jobsCreated: 0,
      jobsWomen: 0,
      jobsMen: 0,
      fundsMobilisedUsd: 0,
    },
    fundingRounds: [],
    lastUpdateAt: '2024-09-30',
    trainerId: 't-esi',
    joinedAt: '2024-09-01',
  },
  {
    id: 'e-healthfirst',
    businessName: 'HealthFirst',
    representative: 'Nadia Asante',
    initials: 'HF',
    email: 'nadia@healthfirst.ng',
    phone: '+234 80 555 0144',
    country: 'Nigeria',
    sector: 'healthtech',
    stage: 'scale',
    contentItemIds: ['c-pitch-structure', 'c-pitch-qa', 'c-pitch-checklist', 'c-finmodel-basics', 'c-market-expansion-map', 'c-export-checklist'],
    programmeIds: ['p-readiness-fintech', 'p-market-expansion', 'p-export-readiness'],
    programmeId: 'p-readiness-fintech',
    source: 'invited',
    goal: {
      type: 'fundraising',
      amountUsd: 1200000,
      description: 'Series A to scale into East African markets.',
    },
    status: 'active',
    metrics: {
      trainingProgress: 80,
      deliverablesDone: 5,
      deliverablesTotal: 8,
      jobsCreated: 12,
      jobsWomen: 8,
      jobsMen: 4,
      fundsMobilisedUsd: 300000,
    },
    fundingRounds: funding['e-healthfirst'],
    periodicUpdates: [
      {
        id: 'pu-hf-q4-2024',
        period: 'Q4 2024',
        periodStart: '2024-10-01',
        periodEnd: '2024-12-31',
        submittedAt: '2024-12-31',
        programmeId: 'p-readiness-fintech',
        jobsWomen: 8,
        jobsMen: 4,
        jobsCreated: 12,
        fundsMobilisedUsd: 0,
        notes: 'Expanded operations team after clinical pilot growth.',
      },
    ],
    lastUpdateAt: '2024-12-31',
    trainerId: 't-kofi',
    joinedAt: '2024-03-01',
  },
  {
    id: 'e-buildit',
    businessName: 'BuildIt',
    representative: 'Tunde Kola',
    initials: 'TK',
    email: 'tunde@buildit.ng',
    phone: '+234 81 555 0111',
    country: 'Nigeria',
    sector: 'construction',
    stage: 'idea',
    source: 'self-registered',
    goal: { type: 'programme-completion' },
    status: 'unassigned',
    metrics: {
      trainingProgress: 0,
      deliverablesDone: 0,
      deliverablesTotal: 0,
      jobsCreated: 0,
      jobsWomen: 0,
      jobsMen: 0,
      fundsMobilisedUsd: 0,
    },
    fundingRounds: [],
    joinedAt: '2025-04-05',
  },
  {
    id: 'e-mediscan',
    businessName: 'MediScan',
    representative: 'Grace Nana',
    initials: 'GN',
    email: 'grace@mediscan.ke',
    phone: '+254 71 555 0123',
    country: 'Kenya',
    sector: 'healthtech',
    stage: 'idea',
    source: 'self-registered',
    goal: { type: 'programme-completion' },
    status: 'unassigned',
    metrics: {
      trainingProgress: 0,
      deliverablesDone: 0,
      deliverablesTotal: 0,
      jobsCreated: 0,
      jobsWomen: 0,
      jobsMen: 0,
      fundsMobilisedUsd: 0,
    },
    fundingRounds: [],
    joinedAt: '2025-04-07',
  },
  {
    id: 'e-edify',
    businessName: 'Edify Learn',
    representative: 'Ama Twum',
    initials: 'EL',
    email: 'ama@edifylearn.gh',
    phone: '+233 24 555 0199',
    country: 'Ghana',
    sector: 'edtech',
    stage: 'growth',
    cohort: 'Cohort 6',
    contentItemIds: ['c-intro-vid', 'c-intro-pdf', 'c-bmc-why', 'c-bmc-sheet', 'c-pitch-structure'],
    programmeIds: ['p-accelerator-c6'],
    programmeId: 'p-accelerator-c6',
    source: 'invited',
    goal: { type: 'milestone', description: 'Reach 10k active learners' },
    status: 'active',
    metrics: {
      trainingProgress: 48,
      deliverablesDone: 2,
      deliverablesTotal: 7,
      jobsCreated: 4,
      jobsWomen: 3,
      jobsMen: 1,
      fundsMobilisedUsd: 0,
    },
    fundingRounds: [],
    periodicUpdates: [
      {
        id: 'pu-edify-q4-2024',
        period: 'Q4 2024',
        periodStart: '2024-10-01',
        periodEnd: '2024-12-31',
        submittedAt: '2024-12-31',
        programmeId: 'p-accelerator-c6',
        jobsWomen: 3,
        jobsMen: 1,
        jobsCreated: 4,
        fundsMobilisedUsd: 0,
        notes: 'Hired learning support team for the pilot cohort.',
      },
    ],
    lastUpdateAt: '2024-12-31',
    joinedAt: '2024-08-12',
  },
];

export const entrepreneurById = (id: string) =>
  entrepreneurs.find((e) => e.id === id);

/** The entrepreneur used as the signed-in user on the entrepreneur side. */
export const currentEntrepreneur = entrepreneurs[0];
