import type { Program, Module, ContentItem } from '@/types';

/**
 * Seed programmes, their modules, and the content items attached to
 * each module. A content item can be reused across modules (mirroring
 * the "reuse" idea in the mockups), and modules can be reused across
 * programmes — the `reuseCount` field drives the "used in 2 programmes"
 * tag.
 */

export const programs: Program[] = [
  {
    id: 'p-accelerator-c6',
    name: 'BID Accelerator – Cohort 6',
    accessType: 'assigned',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    publishedAt: '2025-12-15',
    maxEntrepreneurs: 20,
    description:
      'Core accelerator curriculum covering foundations, business model, fundraising and operations.',
    accent: 'bid',
    entrepreneursCount: 18,
    leftEntrepreneursCount: 2,
    moduleIds: ['m-intro', 'm-bmc', 'm-pitch', 'm-finmodel', 'm-legal'],
    progress: 61,
  },
  {
    id: 'p-readiness-fintech',
    name: 'Investment Readiness for Fintech',
    accessType: 'assigned',
    startDate: '2026-03-01',
    endDate: '2026-09-30',
    publishedAt: '2026-02-10',
    maxEntrepreneurs: 15,
    description:
      'Specialised track on investor relations, due diligence prep and term sheets.',
    accent: 'info',
    entrepreneursCount: 9,
    leftEntrepreneursCount: 1,
    moduleIds: ['m-pitch', 'm-finmodel', 'm-ddprep'],
    progress: 20,
  },
  {
    id: 'p-wee',
    name: 'Women Economic Empowerment Programme',
    accessType: 'free',
    startDate: '2026-09-01',
    endDate: '2026-11-30',
    maxEntrepreneurs: 25,
    description:
      'Programme supporting women-led ventures with tailored training and mentoring.',
    accent: 'success',
    entrepreneursCount: 20,
    leftEntrepreneursCount: 4,
    moduleIds: ['m-intro'],
    progress: 12,
  },
  {
    id: 'p-growth-ops',
    name: 'Growth Operations Sprint',
    accessType: 'assigned',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    publishedAt: '2026-03-15',
    maxEntrepreneurs: 18,
    description: 'Short sprint for operating cadence, hiring plans, and weekly performance reviews.',
    accent: 'bid',
    entrepreneursCount: 11,
    leftEntrepreneursCount: 1,
    moduleIds: ['m-growth-ops'],
    progress: 42,
  },
  {
    id: 'p-market-expansion',
    name: 'Market Expansion Readiness',
    accessType: 'assigned',
    startDate: '2026-05-01',
    endDate: '2026-08-31',
    publishedAt: '2026-04-12',
    maxEntrepreneurs: 12,
    description: 'Prepare route-to-market, partner channels, and country launch assumptions.',
    accent: 'info',
    entrepreneursCount: 7,
    leftEntrepreneursCount: 0,
    moduleIds: ['m-market-expansion'],
    progress: 35,
  },
  {
    id: 'p-leadership-lab',
    name: 'Founder Leadership Lab',
    accessType: 'assigned',
    startDate: '2026-07-01',
    endDate: '2026-10-31',
    publishedAt: '2026-06-10',
    maxEntrepreneurs: 16,
    description: 'Leadership routines for founder resilience, delegation, and operating rhythm.',
    accent: 'success',
    entrepreneursCount: 10,
    leftEntrepreneursCount: 0,
    moduleIds: ['m-leadership-lab'],
    progress: 18,
  },
  {
    id: 'p-export-readiness',
    name: 'Export Readiness Clinic',
    accessType: 'assigned',
    startDate: '2026-08-01',
    endDate: '2026-11-15',
    publishedAt: '2026-07-02',
    maxEntrepreneurs: 10,
    description: 'Clinic for documentation, pricing, logistics, and buyer conversations across borders.',
    accent: 'bid',
    entrepreneursCount: 6,
    leftEntrepreneursCount: 0,
    moduleIds: ['m-export-readiness'],
    progress: 8,
  },
];

export const modules: Module[] = [
  {
    id: 'm-intro',
    order: 1,
    title: 'Introduction to Entrepreneurship in Africa',
    description: 'Foundational orientation to the African startup landscape.',
    contentItemIds: ['c-intro-vid', 'c-intro-pdf'],
    reuseCount: 2,
  },
  {
    id: 'm-bmc',
    order: 2,
    title: 'Business Model Canvas Deep Dive',
    description: 'Map and iterate on every block of the BMC.',
    contentItemIds: ['c-bmc-why', 'c-bmc-sheet', 'c-bmc-valueprop', 'c-bmc-tool'],
    reuseCount: 2,
  },
  {
    id: 'm-pitch',
    order: 3,
    title: 'Investor Pitch Fundamentals',
    description: 'Structure, deliver and defend your investor pitch.',
    contentItemIds: ['c-pitch-structure', 'c-pitch-qa', 'c-pitch-checklist'],
    reuseCount: 2,
  },
  {
    id: 'm-finmodel',
    order: 4,
    title: 'Financial Modelling for Early-Stage Startups',
    description: 'Build a 3-year operating model.',
    contentItemIds: ['c-finmodel-basics'],
  },
  {
    id: 'm-legal',
    order: 5,
    title: 'Legal Structures for Startups',
    description: 'Choose the right entity and equity structure.',
    contentItemIds: [],
  },
  {
    id: 'm-ddprep',
    order: 1,
    title: 'Due Diligence Preparation',
    description: 'Get your data room and disclosures ready for investors.',
    contentItemIds: [],
  },
  {
    id: 'm-growth-ops',
    order: 1,
    title: 'Growth Operating System',
    description: 'Set weekly metrics, decision cadence, and hiring priorities.',
    contentItemIds: ['c-growth-ops-cadence'],
  },
  {
    id: 'm-market-expansion',
    order: 1,
    title: 'Market Expansion Planning',
    description: 'Compare target markets and define launch assumptions.',
    contentItemIds: ['c-market-expansion-map'],
  },
  {
    id: 'm-leadership-lab',
    order: 1,
    title: 'Founder Leadership Routines',
    description: 'Build delegation rituals and founder operating habits.',
    contentItemIds: ['c-leadership-routines'],
  },
  {
    id: 'm-export-readiness',
    order: 1,
    title: 'Export Readiness Checklist',
    description: 'Prepare pricing, documentation, and logistics before buyer outreach.',
    contentItemIds: ['c-export-checklist'],
  },
];

export const contentItems: ContentItem[] = [
  {
    id: 'c-intro-vid',
    title: 'Welcome & overview',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '18 min',
    moduleId: 'm-intro',
    trainerId: 't-kofi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'completed',
  },
  {
    id: 'c-intro-pdf',
    title: 'Reading list',
    chapter: 'Chapter 1',
    type: 'pdf',
    durationLabel: 'Downloadable',
    moduleId: 'm-intro',
    trainerId: 't-kofi',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    progress: 'completed',
  },
  {
    id: 'c-bmc-why',
    title: 'Why the canvas matters',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '9 min',
    moduleId: 'm-bmc',
    trainerId: 't-kofi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'completed',
  },
  {
    id: 'c-bmc-sheet',
    title: 'BMC worksheet',
    chapter: 'Chapter 1',
    type: 'pdf',
    durationLabel: 'Downloadable',
    moduleId: 'm-bmc',
    trainerId: 't-kofi',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    progress: 'completed',
  },
  {
    id: 'c-bmc-valueprop',
    title: 'Mapping your value proposition',
    chapter: 'Chapter 2',
    type: 'video',
    durationLabel: '15 min',
    moduleId: 'm-bmc',
    trainerId: 't-esi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'in-progress',
  },
  {
    id: 'c-bmc-tool',
    title: 'Interactive BMC builder',
    chapter: 'Chapter 2',
    type: 'tool',
    durationLabel: 'Embedded tool',
    moduleId: 'm-bmc',
    trainerId: 't-esi',
    toolUrl: 'https://example.com',
    progress: 'not-started',
  },
  {
    id: 'c-pitch-structure',
    title: 'Pitch structure',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '16 min',
    moduleId: 'm-pitch',
    trainerId: 't-kofi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'completed',
  },
  {
    id: 'c-pitch-qa',
    title: 'Handling investor Q&A',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '12 min',
    moduleId: 'm-pitch',
    trainerId: 't-kofi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'completed',
  },
  {
    id: 'c-pitch-checklist',
    title: 'Pitch checklist',
    chapter: 'Chapter 1',
    type: 'pdf',
    durationLabel: 'Downloadable',
    moduleId: 'm-pitch',
    trainerId: 't-kofi',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    progress: 'completed',
  },
  {
    id: 'c-finmodel-basics',
    title: 'Financial modelling basics',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '22 min',
    moduleId: 'm-finmodel',
    trainerId: 't-esi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'not-started',
  },
  {
    id: 'c-growth-ops-cadence',
    title: 'Weekly operating cadence',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '14 min',
    moduleId: 'm-growth-ops',
    trainerId: 't-kofi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'in-progress',
  },
  {
    id: 'c-market-expansion-map',
    title: 'Market selection map',
    chapter: 'Chapter 1',
    type: 'pdf',
    durationLabel: 'Downloadable',
    moduleId: 'm-market-expansion',
    trainerId: 't-esi',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    progress: 'not-started',
  },
  {
    id: 'c-leadership-routines',
    title: 'Delegation and founder routines',
    chapter: 'Chapter 1',
    type: 'video',
    durationLabel: '11 min',
    moduleId: 'm-leadership-lab',
    trainerId: 't-kofi',
    muxPlaybackId: 'DS00Spx1CV902MCtPj5WknGlR102V5HFkDe',
    progress: 'not-started',
  },
  {
    id: 'c-export-checklist',
    title: 'Export readiness checklist',
    chapter: 'Chapter 1',
    type: 'pdf',
    durationLabel: 'Downloadable',
    moduleId: 'm-export-readiness',
    trainerId: 't-esi',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    progress: 'not-started',
  },
];

export const programById = (id?: string) =>
  id ? programs.find((p) => p.id === id) : undefined;

export const moduleById = (id?: string) =>
  id ? modules.find((m) => m.id === id) : undefined;

export const contentItemById = (id: string) =>
  contentItems.find((c) => c.id === id);

export const modulesForProgram = (programId: string) => {
  const program = programById(programId);
  if (!program) return [];
  return modules
    .filter((m) => program.moduleIds.includes(m.id))
    .sort((a, b) => a.order - b.order);
};

export const contentForModule = (moduleId: string) =>
  contentItems.filter((c) => c.moduleId === moduleId);
