export {
  useMarkAllNotificationsReadMutation,
  useMarkNotificationReadMutation,
  useNotificationPreferenceGroupsQuery,
  useNotificationAutomationPreferenceQuery,
  useNotificationPreferencesQuery,
  useNotificationsInfiniteQuery,
  useNotificationSummaryQuery,
  useUpdateNotificationPreferenceGroupMutation,
  useUpdateNotificationAutomationPreferenceMutation,
  useUpdateNotificationPreferenceMutation,
} from "./hooks";
export type {
  NotificationPreference,
  NotificationAutomationPreference,
  NotificationAutomationPreferenceUpdate,
  NotificationPreferenceGroup,
  NotificationPreferenceGroupName,
  NotificationPreferenceUpdate,
  NotificationPreferenceMode,
  NotificationRecord,
  NotificationSeverity,
  NotificationSummary,
  NotificationType,
} from "./types";
