import type { Route } from 'next';

export const routes = {
  home: '/',
  auth: {
    login: '/auth/login',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    acceptInvitation: '/auth/accept-invitation',
    verifyEmail: '/auth/verify-email',
    onboarding: '/auth/onboarding',
  },
  entrepreneur: {
    dashboard: '/entrepreneur/dashboard',
    training: '/entrepreneur/training',
    trainingProgram: (programmeId: string): Route => `/entrepreneur/training/${programmeId}` as Route,
    trainingModule: (programmeId: string, moduleId: string): Route => `/entrepreneur/training/${programmeId}?module=${moduleId}` as Route,
    profile: '/entrepreneur/profile',
    deliverables: '/entrepreneur/deliverables',
    deliverableGroup: (groupId: string): Route => `/entrepreneur/deliverables/${groupId}` as Route,
    deliverableDetail: (
      programmeId: string,
      deliverableId: string,
      deliverableName: string,
    ): Route =>
      `/entrepreneur/deliverables/${encodeURIComponent(programmeId)}?deliverableId=${encodeURIComponent(deliverableId)}&search=${encodeURIComponent(deliverableName)}` as Route,
    schedule: '/entrepreneur/schedule',
    tools: '/entrepreneur/tools',
  },
  trainer: {
    dashboard: '/trainer/dashboard',
    entrepreneurs: '/trainer/entrepreneurs',
    programmes: '/trainer/programmes',
    programme: (programId: string): Route => `/trainer/programmes/${programId}` as Route,
    deliverableReviews: '/trainer/deliverable-reviews',
    sessions: '/trainer/sessions',
    settings: '/trainer/settings',
  },
  admin: {
    dashboard: '/admin/dashboard',
    admins: '/admin/admins',
    entrepreneurs: '/admin/entrepreneurs',
    trainers: '/admin/trainers',
    programs: '/admin/programs',
    program: (programId: string): Route => `/admin/programs/${programId}` as Route,
    content: '/admin/content',
    contentModule: (moduleId: string): Route => `/admin/content?moduleId=${moduleId}` as Route,
    entrepreneurTools: '/admin/entrepreneur-tools',
    deliverableReviews: '/admin/deliverable-reviews',
    sessions: '/admin/sessions',
    toolRequests: '/admin/tool-requests',
    stagesSectors: '/admin/stages-sectors',
    settings: '/admin/settings',
    settingsStages: '/admin/settings/stages',
    settingsSectors: '/admin/settings/sectors',
    settingsGoalTypes: '/admin/settings/goal-types',
    settingsToolAreas: '/admin/settings/tool-areas',
    settingsCompany: '/admin/settings/company',
    reporting: '/admin/reporting',
    health: '/admin/health',
  },
} as const;

export type AppRoute = typeof routes;
