export const routes = {
  home: '/',
  auth: {
    login: '/auth/login',
    signup: '/auth/signup',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    onboarding: '/auth/onboarding',
  },
  entrepreneur: {
    dashboard: '/entrepreneur/dashboard',
    training: '/entrepreneur/training',
    trainingProgram: (programmeId: string) => `/entrepreneur/training/${programmeId}`,
    trainingModule: (programmeId: string, moduleId: string) =>
      `/entrepreneur/training/${programmeId}/${moduleId}`,
    profile: '/entrepreneur/profile',
    deliverables: '/entrepreneur/deliverables',
    deliverableGroup: (groupId: string) => `/entrepreneur/deliverables/${groupId}`,
    schedule: '/entrepreneur/schedule',
    tools: '/entrepreneur/tools',
  },
  trainer: {
    dashboard: '/trainer/dashboard',
    entrepreneurs: '/trainer/entrepreneurs',
    programmes: '/trainer/programmes',
    programme: (programId: string) => `/trainer/programmes/${programId}`,
    deliverableReviews: '/trainer/deliverable-reviews',
    sessions: '/trainer/sessions',
    settings: '/trainer/settings',
  },
  admin: {
    dashboard: '/admin/dashboard',
    admins: '/admin/admins',
    entrepreneurs: '/admin/entrepreneurs',
    trainers: '/admin/trainers',
    programs: '/admin/programs',
    program: (programId: string) => `/admin/programs/${programId}`,
    content: '/admin/content',
    entrepreneurTools: '/admin/entrepreneur-tools',
    deliverableReviews: '/admin/deliverable-reviews',
    sessions: '/admin/sessions',
    toolRequests: '/admin/tool-requests',
    stagesSectors: '/admin/stages-sectors',
    settings: '/admin/settings',
    settingsStages: '/admin/settings/stages',
    settingsSectors: '/admin/settings/sectors',
    settingsGoalTypes: '/admin/settings/goal-types',
    settingsCompany: '/admin/settings/company',
    reporting: '/admin/reporting',
  },
} as const;

export type AppRoute = typeof routes;
